spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftec?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
ftec:
  email:
    mail-login: yjcjdrf@gmail.com
    mail-password: qwerty123456789